[package]
name = "sousarc-content-types"
version = "0.1.0"
edition = "2024"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.ulid]
version = "1"
features = ["serde"]

[dependencies.indexmap]
version = "2"
features = ["serde"]

[dependencies]
tracing = "0.1"
rmp-serde = "1"